site_name: {{mkdocs.site_name}}
site_description: Documentación para {{mkdocs.site_name}}
plugins:
  - techdocs-core
nav:
  - Readme: README.md
  - Documentation: documentation.md
  - Error Catalog: errors.md